<script src="{{ site.url }}assets/scripts/site.min.js"></script>

<script>
  Reveal.initialize({
    controls: false,
    progress: false,
    overview: false,
    fragments: false,
    help: false,
    mouseWheel: true,
    center: true,

    width: "100%",
    height: "100%",

		transition: 'slide', // none/fade/slide/convex/concave/zoom

		// Optional reveal.js plugins
		dependencies: []
  });
</script>

</body>
</html>
